---
title: "exploration"
author: "Jordan Boswell and Thuy Nguyen"
date: "2/26/2022"
output: html_document
---

```{r}
library(rigr)
library(tidyverse)
library(randomForest)
library(caret)
```

# Read data and format columns
```{r}
ship <- read.csv("train.csv")

ship$GID <- as.integer(substr(ship$PassengerId, 1,4))

ship$IID <- as.integer(substr(ship$PassengerId,6,8))

ship$GroupSize <- sapply(ship$GID, function(x){sum(ship$GID == x)})

ship$HomePlanet <- as.factor(ship$HomePlanet)

ship$CryoSleep <- as.factor(ship$CryoSleep)

ship$Deck <- as.character(mapply(function(x,y){if(nchar(x)==0){NULL}else{substr(x,y[2],y[3]-2)}},
                      ship$Cabin,
                      regexec("(.*?)/(.*?)/(.*)", ship$Cabin)))
ship$Num <- as.character(mapply(function(x,y){if(nchar(x)==0){NULL}else{substr(x,y[3],y[4]-2)}},
                      ship$Cabin,
                      regexec("(.*?)/(.*?)/(.*)", ship$Cabin)))
ship$Side <- as.character(mapply(function(x,y){if(nchar(x)==0){NULL}else{substr(x,y[4],nchar(x))}},
                      ship$Cabin,
                      regexec("(.*?)/(.*?)/(.*)", ship$Cabin)))
ship$Cabin <- sapply(ship$Cabin, function(x){if (x=="") NA else x})

ship$Destination <- as.factor(ship$Destination)

ship$Age <- as.integer(ship$Age)

ship$VIP <- as.logical(ship$VIP)

ship$Transported <- as.logical(ship$Transported)

```

# Fixing missing data
```{r}
ship[ship$CryoSleep %in% T, c("RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck")] <- 0

```


# Other notes
Test and train's GID are disjoint.
```{r}
test <- read.csv("test.csv")
test$GID <- as.integer(substr(test$PassengerId, 1,4))
intersect(test$GID, ship$GID)
```


`


# Check Cabin for people with same GID

```{r}
cmplt <- complete.cases(ship[,c("GID", "Cabin")])
count = 0
for(i in 1: nrow(ship)){
  if (cmplt[i] == F) next
  for(j in i:nrow(ship)){
    if(cmplt[j] ==F) next
    if(ship$GID[i]== ship$GID[j] & ship$Cabin[i] !=ship$Cabin[j] & ship$Deck[i] %in% c("A","B","C")& ship$Deck[j] %in% c("A","B","C"))
      count =count +1
      #print(paste0("Same GID; differ Cabin: ", i, ", ", j, ship$Deck[i], ship$Deck[j]))
  }
  }
```


0.

All same group, different cabin are not in A, B,c( except rows 5162AB", 4942AC)

# same cabin, diffent GID

```{r}
cmplt <- complete.cases(ship[,c("GID", "Cabin")])
for(i in 1: nrow(ship)){
  if (cmplt[i] == FALSE) next
  for(j in i:nrow(ship)){
    if(cmplt[j] ==FALSE) next
    if(ship$GID[i]!= ship$GID[j] & ship$Cabin[i] ==ship$Cabin[j])
        print(paste0("Same Cabin; different GID: ", i, ", ", j, ship$Deck[i], ship$Deck[j]))
  }
}
```

No one same cabin but different GID

# Test

```{r}
ship_test <- read.csv("test.csv")

ship_test$GID <- as.integer(substr(ship_test$PassengerId, 1,4))

ship_test$IID <- as.integer(substr(ship_test$PassengerId,6,8))

ship_test$GroupSize <- sapply(ship_test$GID, function(x){sum(ship_test$GID == x)})

ship_test$HomePlanet <- as.factor(ship_test$HomePlanet)

ship_test$CryoSleep <- as.factor(ship_test$CryoSleep)

ship_test$Deck <- as.character(mapply(function(x,y){if(nchar(x)==0){NULL}else{substr(x,y[2],y[3]-2)}},
                      ship_test$Cabin,
                      regexec("(.*?)/(.*?)/(.*)", ship_test$Cabin)))
ship_test$Num <- as.character(mapply(function(x,y){if(nchar(x)==0){NULL}else{substr(x,y[3],y[4]-2)}},
                      ship_test$Cabin,
                      regexec("(.*?)/(.*?)/(.*)", ship_test$Cabin)))
ship_test$Side <- as.character(mapply(function(x,y){if(nchar(x)==0){NULL}else{substr(x,y[4],nchar(x))}},
                      ship_test$Cabin,
                      regexec("(.*?)/(.*?)/(.*)", ship_test$Cabin)))
ship_test$Cabin <- sapply(ship_test$Cabin, function(x){if (x=="") NA else x})

ship_test$Destination <- as.factor(ship_test$Destination)

ship_test$Age <- as.integer(ship_test$Age)

ship_test$VIP <- as.logical(ship_test$VIP)

ship_test[ship_test$CryoSleep %in% T, c("RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck")] <- 0

```



#Model 1
```{r}

t1<-regress("odds", Transported~ Deck+ GID+CryoSleep+Age+VIP+HomePlanet+RoomService+FoodCourt+ShoppingMall,
            data = ship[complete.cases(ship),])

pred <- predict(t, newdata= ship_test[complete.cases(ship_test),])>0.5

ship_test$Transported[complete.cases(ship_test)] = pred
ship_test$Transported[!complete.cases(ship_test)] = TRUE
ship_test$Transported <- ifelse(ship_test$Transported == "TRUE","True", "False")
#write.csv(ship_test[,c("PassengerId", "Transported")], quote= FALSE,row.names = FALSE,file = "submission.csv")
```


